[package]
name = "obsidian-achievements"
version = "0.0.9"
authors = ["Zachatoo"]
description = "Add achievements to Obsidian."
license = "MIT"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3.49"
